# Generated by Django 4.1.3 on 2024-06-02 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_orderitem_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='size',
        ),
    ]
